/**
 * DO NOT EDIT DIRECTLY
 * Generated by Style Dictionary
 */

export default {
  "colors": {
    "web": {
      "system": {
        "color": {
          "impression": {
            "primary_asagi": {
              "value": "#00757E"
            },
            "onPrimary_asagi": {
              "value": "#FFFFFF"
            },
            "secondary_asagi": {
              "value": "#015C63"
            },
            "onSecondary_asagi": {
              "value": "#FFFFFF"
            },
            "tertiary_asagi": {
              "value": "#EFEEEB"
            },
            "onTertiary_asagi": {
              "value": "#02373C"
            },
            "subtle_asagi": {
              "value": "#D9F6FC"
            },
            "primary_konjo": {
              "value": "#0A69CF"
            },
            "onPrimary_konjo": {
              "value": "#FFFFFF"
            },
            "secondary_konjo": {
              "value": "#0650A0"
            },
            "onSecondary_konjo": {
              "value": "#FFFFFF"
            },
            "tertiary_konjo": {
              "value": "#EFF2FC"
            },
            "onTertiary_konjo": {
              "value": "#073165"
            },
            "subtle_konjo": {
              "value": "#EFF2FC"
            },
            "primary_kurikawa": {
              "value": "#AB4919"
            },
            "onPrimary_kurikawa": {
              "value": "#FFFFFF"
            },
            "secondary_kurikawa": {
              "value": "#803510"
            },
            "onSecondary_kurikawa": {
              "value": "#FFFFFF"
            },
            "tertiary_kurikawa": {
              "value": "#AB4919"
            },
            "onTertiary_kurikawa": {
              "value": "#FFFFFF"
            },
            "subtle_kurikawa": {
              "value": "#FAECE6"
            },
            "primary_sumire": {
              "value": "#914DA9"
            },
            "onPrimary_sumire": {
              "value": "#FFFFFF"
            },
            "secondary_sumire": {
              "value": "#733B85"
            },
            "onSecondary_sumire": {
              "value": "#FFFFFF"
            },
            "tertiary_sumire": {
              "value": "#043F81"
            },
            "onTertiary_sumire": {
              "value": "#FFFFFF"
            },
            "subtle_sumire": {
              "value": "#F4ECF6"
            },
            "primary_tsutsuji": {
              "value": "#B9336B"
            },
            "onPrimary_tsutsuji": {
              "value": "#FFFFFF"
            },
            "secondary_tsutsuji": {
              "value": "#932653"
            },
            "onSecondary_tsutsuji": {
              "value": "#FFFFFF"
            },
            "tertiary_tsutsuji": {
              "value": "#F9EBF0"
            },
            "onTertiary_tsutsuji": {
              "value": "#591734"
            },
            "subtle_tsutsuji": {
              "value": "#F9EBF0"
            }
          },
          "component": {
            "surface_asagi": {
              "value": "#FFFFFF"
            },
            "onSurface_asagi": {
              "value": "#02373C"
            },
            "surfaceDim_asagi": {
              "value": "#EFEEEB"
            },
            "surfaceDimmest_asagi": {
              "value": "#AFAEAA"
            },
            "surface_konjo": {
              "value": "#FFFFFF"
            },
            "onSurface_konjo": {
              "value": "#073165"
            },
            "surfaceDim_konjo": {
              "value": "#EFEEEB"
            },
            "surfaceDimmest_konjo": {
              "value": "#AFAEAA"
            },
            "surface_kurikawa": {
              "value": "#FFFFFF"
            },
            "onSurface_kurikawa": {
              "value": "#50230D"
            },
            "surfaceDim_kurikawa": {
              "value": "#EFEEEB"
            },
            "surfaceDimmest_kurikawa": {
              "value": "#AFAEAA"
            },
            "surface_sumire": {
              "value": "#FFFFFF"
            },
            "onSurface_sumire": {
              "value": "#462352"
            },
            "surfaceDim_sumire": {
              "value": "#EFEEEB"
            },
            "surfaceDimmest_sumire": {
              "value": "#AFAEAA"
            },
            "surface_tsutsuji": {
              "value": "#FFFFFF"
            },
            "onSurface_tsutsuji": {
              "value": "#591734"
            },
            "surfaceDim_tsutsuji": {
              "value": "#EFEEEB"
            },
            "surfaceDimmest_tsutsuji": {
              "value": "#AFAEAA"
            }
          },
          "mvShape": {
            "foreground": {
              "arc": {
                "index_asagi": {
                  "value": "#00A3AF"
                },
                "indexBorder_asagi": {
                  "value": "#98E1C8"
                },
                "extraBold_asagi": {
                  "value": "#98E1C8"
                },
                "bold_asagi": {
                  "value": "#00757E"
                },
                "normal_asagi": {
                  "value": "#EB4F8E"
                },
                "thin_asagi": {
                  "value": "#F7C6B0"
                },
                "index_konjo": {
                  "value": "#428CFE"
                },
                "indexBorder_konjo": {
                  "value": "#BFCEFC"
                },
                "extraBold_konjo": {
                  "value": "#BFCEFC"
                },
                "bold_konjo": {
                  "value": "#0650A0"
                },
                "normal_konjo": {
                  "value": "#F84258"
                },
                "thin_konjo": {
                  "value": "#F2DBC0"
                },
                "index_kurikawa": {
                  "value": "#F49567"
                },
                "indexBorder_kurikawa": {
                  "value": "#EDC18A"
                },
                "extraBold_kurikawa": {
                  "value": "#EDC18A"
                },
                "bold_kurikawa": {
                  "value": "#803510"
                },
                "normal_kurikawa": {
                  "value": "#BFCEFC"
                },
                "thin_kurikawa": {
                  "value": "#DCBDE4"
                },
                "index_sumire": {
                  "value": "#CC9FD9"
                },
                "indexBorder_sumire": {
                  "value": "#BFCEFC"
                },
                "extraBold_sumire": {
                  "value": "#BFCEFC"
                },
                "bold_sumire": {
                  "value": "#462352"
                },
                "normal_sumire": {
                  "value": "#EDC18A"
                },
                "thin_sumire": {
                  "value": "#8FAEFE"
                },
                "index_tsutsuji": {
                  "value": "#EB4F8E"
                },
                "indexBorder_tsutsuji": {
                  "value": "#F7C6B0"
                },
                "extraBold_tsutsuji": {
                  "value": "#F7C6B0"
                },
                "bold_tsutsuji": {
                  "value": "#B9336B"
                },
                "normal_tsutsuji": {
                  "value": "#00A3AF"
                },
                "thin_tsutsuji": {
                  "value": "#BFCEFC"
                }
              },
              "rectangle": {
                "oblong_asagi": {
                  "value": "#F9EBF0"
                },
                "square_asagi": {
                  "value": "#D7DEFB"
                },
                "oblong_konjo": {
                  "value": "#FCEBEA"
                },
                "square_konjo": {
                  "value": "#AEEAD5"
                },
                "oblong_kurikawa": {
                  "value": "#D7DEFB"
                },
                "square_kurikawa": {
                  "value": "#FDB9B4"
                },
                "oblong_sumire": {
                  "value": "#F2DBC0"
                },
                "square_sumire": {
                  "value": "#F5C1D1"
                },
                "oblong_tsutsuji": {
                  "value": "#F4ECF6"
                },
                "square_tsutsuji": {
                  "value": "#CAF9E6"
                }
              }
            },
            "background": {
              "arc": {
                "first_asagi": {
                  "value": "#64CCD3"
                },
                "second_asagi": {
                  "value": "#BFCEFC"
                },
                "third_asagi": {
                  "value": "#98E1C8"
                },
                "fourth_asagi": {
                  "value": "#D9D8D3"
                },
                "fifth_asagi": {
                  "value": "#64CCD3"
                },
                "first_konjo": {
                  "value": "#8FAEFE"
                },
                "second_konjo": {
                  "value": "#9CE6EC"
                },
                "third_konjo": {
                  "value": "#8FAEFE"
                },
                "fourth_konjo": {
                  "value": "#C3EFF4"
                },
                "fifth_konjo": {
                  "value": "#8FAEFE"
                },
                "first_kurikawa": {
                  "value": "#E26324"
                },
                "second_kurikawa": {
                  "value": "#AF8245"
                },
                "third_kurikawa": {
                  "value": "#F49567"
                },
                "fourth_kurikawa": {
                  "value": "#846132"
                },
                "fifth_kurikawa": {
                  "value": "#E26324"
                },
                "first_sumire": {
                  "value": "#AA61C2"
                },
                "second_sumire": {
                  "value": "#0A69CF"
                },
                "third_sumire": {
                  "value": "#CC9FD9"
                },
                "fourth_sumire": {
                  "value": "#073165"
                },
                "fifth_sumire": {
                  "value": "#914DA9"
                },
                "first_tsutsuji": {
                  "value": "#F190B4"
                },
                "second_tsutsuji": {
                  "value": "#FDB9B4"
                },
                "third_tsutsuji": {
                  "value": "#F190B4"
                },
                "fourth_tsutsuji": {
                  "value": "#FCD6D3"
                },
                "fifth_tsutsuji": {
                  "value": "#F190B4"
                }
              }
            }
          },
          "articleFigure": {
            "foreground": {
              "primary_asagi": {
                "value": "#64CCD3"
              },
              "onPrimary_asagi": {
                "value": "#00757E"
              },
              "secondary_asagi": {
                "value": "#CC9FD9"
              },
              "tertiary_asagi": {
                "value": "#D9F6FC"
              },
              "surface_asagi": {
                "value": "#FFFFFF"
              },
              "onSurface_asagi": {
                "value": "#000000"
              },
              "primary_konjo": {
                "value": "#8FAEFE"
              },
              "onPrimary_konjo": {
                "value": "#0A69CF"
              },
              "secondary_konjo": {
                "value": "#64CCD3"
              },
              "tertiary_konjo": {
                "value": "#EFF2FC"
              },
              "surface_konjo": {
                "value": "#FFFFFF"
              },
              "onSurface_konjo": {
                "value": "#000000"
              },
              "primary_kurikawa": {
                "value": "#F49567"
              },
              "onPrimary_kurikawa": {
                "value": "#803510"
              },
              "secondary_kurikawa": {
                "value": "#DAA358"
              },
              "tertiary_kurikawa": {
                "value": "#F7EDE2"
              },
              "surface_kurikawa": {
                "value": "#FFFFFF"
              },
              "onSurface_kurikawa": {
                "value": "#000000"
              },
              "primary_sumire": {
                "value": "#CC9FD9"
              },
              "onPrimary_sumire": {
                "value": "#733B85"
              },
              "secondary_sumire": {
                "value": "#8FAEFE"
              },
              "tertiary_sumire": {
                "value": "#F4ECF6"
              },
              "surface_sumire": {
                "value": "#FFFFFF"
              },
              "onSurface_sumire": {
                "value": "#000000"
              },
              "primary_tsutsuji": {
                "value": "#F190B4"
              },
              "onPrimary_tsutsuji": {
                "value": "#B9336B"
              },
              "secondary_tsutsuji": {
                "value": "#CC9FD9"
              },
              "tertiary_tsutsuji": {
                "value": "#F9EBF0"
              },
              "surface_tsutsuji": {
                "value": "#FFFFFF"
              },
              "onSurface_tsutsuji": {
                "value": "#000000"
              }
            },
            "background_asagi": {
              "value": "#f5f5f5"
            },
            "background_konjo": {
              "value": "#f5f5f5"
            },
            "background_kurikawa": {
              "value": "#f5f5f5"
            },
            "background_sumire": {
              "value": "#f5f5f5"
            },
            "background_tsutsuji": {
              "value": "#f5f5f5"
            }
          }
        }
      }
    }
  }
}